### ISSUE TITLE
在 Raspberry Pi 搭建Web服务器

### ISSUE THREAD

**Issue by SailCPU** [SailCPU/YSCProject#6]

**Comment by FanMover** [comment]
Set up your Arduino and Raspberry Pi to control lighting and animation on an RGB LED strip from your smartphone or PC.
[(link)](https://www.hackster.io/bportaluri/web-controlled-led-animations-with-raspberry-pi-and-arduino-112025)

**Comment by SailCPU** [comment]
是的，就是把这个拿过来
