### ISSUE TITLE
建立Arduino 与 Raspberry Pi 数据交换机制

### ISSUE THREAD

**Issue by SailCPU** [SailCPU/YSCProject#7]
初步选用串口来实现

**Comment by FanMover** [comment]
[Web-Controlled LED Animations with Raspberry Pi and Arduino](https://www.hackster.io/bportaluri/web-controlled-led-animations-with-raspberry-pi-and-arduino-112025)

**Comment by FanMover** [comment]
Arduino 与 RaspPi通过串口通信，具体通信协议要定义。RaspPi与Console通过 web来确定。
